### PR TITLE
fix bug where current stakers may not be removed when they should be

### PR DESCRIPTION
**Pull request by danlaine**
I'm gonna add some tests for this, too

### CODE REVIEW

**Review by StephenButtolph — COMMENTED** [review]
This should break from the `currentStakerLoop` as well to return the iterator errors correctly.

**Comment by danlaine** [comment]
> This should break from the `currentStakerLoop` as well to return the iterator errors correctly.

fixed

**Review by StephenButtolph — COMMENTED** [review]
Can we add a regression test for this functionality?

**Comment by danlaine** [comment]
> Can we add a regression test for this functionality?

added

**Review by StephenButtolph — APPROVED** [review]

**Pull request merged**
