### PR TITLE
limit number of concurrent tls connection establishments

### PR DESCRIPTION
**Pull request by cryptonote-social**
avalanchego on startup or following networking connectivity issues will attempt to accept and/or initiate a thousand+ TLS connections simultaneously, which can cause network saturation and timeouts, possibly leading to the timeout death spiral I have reported in issue [874](https://github.com/ava-labs/avalanchego/issues/874).

Testing: I am currently running my validator with this PR applied and so far it has run reliably, though I can't say for sure it completely fixes the issue since I am unable to reliably replicate it (it strikes me randomly every week or two).  Nevertheless the CPU profile indicates a huge fraction of the CPU usage being taken up by connection TLS handshakes, so it seems likely to be a culprit.

I have set the default concurrency to 64, but I have tested that avalanchego starts up & bootstraps promptly for values all the way down to 32 and all the way up to 512. I am not sure what the "ideal" setting should be but 64 seems like it should be safe for a validator on a slower connection like mine.

### CODE REVIEW

**Comment by cryptonote-social** [comment]
Well unfortunately the validator Issue resurfaced last night so this PR, while still probably valuable, does not seem to fix it 100%.

**Comment by danlaine** [comment]
Hey thanks for making this PR. I'll try to review it this week. For what it's worth, we already support rate-limiting outgoing connection attempts, but I think it's worth considering rate-limiting incoming attempts as well.

**Comment by cryptonote-social** [comment]
Yes I see the limiting on sending messages over outgoing connections, but there is no limit on the # of concurrent outgoing connection attempts (unless those attempts start timing out...).  This PR puts a hard cap on the # of concurrent connection establishments (whether incoming or outgoing).

**Comment by cryptonote-social** [comment]
let me know if you have ideas on how I might reproduce this issue, because until then this is all guesswork. I've tried things like yanking the network cable out of the server for a bit, which does make it go nuts for a while after I plug it back in, but so far it's always recovered nicely while I'm watching it :/

**Comment by danlaine** [comment]
AvalancheGo now supports rate-limiting of inbound connections. See https://docs.avax.network/build/references/command-line-interface#connection-rate-limiting

**Pull request closed without merging**
