### PR TITLE
remove duplicate From field in avm.SendArgs struct

### PR DESCRIPTION
**Pull request by jpop32**
From field is already present in api.JSONSpendHeader

### CODE REVIEW

**Comment by el33th4x0r** [comment]
Will this break clients that used to supply this argument?

Seems like it should be optional.

If supplied, the value here should match the other from field.

**Comment by danlaine** [comment]
@el33th4x0r 
`Will this break clients that used to supply this argument?`
No, the API specification is exactly the same as before.

**Comment by jpop32** [comment]
The From field is still there, in the included api.JSONSpendHeader (it actually includes JSONFromAddrs, which only has From []string field). Any supplied From argument would end there in both cases.

I now noticed that there is the same situation in avm.SengArgsMultiple too.

**Comment by el33th4x0r** [comment]
Ah, got it, thanks.

**Comment by jpop32** [comment]
Will close this and resubmit after merging test fix from @danlaine, and removing the same extra field in avm.SendMultipleArgs.

**Pull request closed without merging**
