### PR TITLE
Fix Snowman Engine outstanding requests metric

### PR DESCRIPTION
**Pull request by danlaine**

### CODE REVIEW

**Comment by StephenButtolph** [comment]
Why does this fix the issue? shouldn't these requests be cleared once `issue` is called inside of `issueFrom`?

**Comment by danlaine** [comment]
`blkReqs` tracks blocks we've requested but not received...when we receive them (in `Put` and `PushQuery`) we should mark that we've received them.

We might be able to remove the `t.blkReqs.RemoveAny(blkID)` in `issue` but it doesn't hurt to keep it

**Comment by StephenButtolph** [comment]
I mean, I don't really care where the call is... but it seems like this change doesn't actually change any behavior, because the call is already made in `issue`. Is there a path in the code that I'm missing such that this call is actually required to be in `Put` and `PushQuery`?

**Comment by danlaine** [comment]
Hmm...`issueFrom` should call `issue`, which calls `RemoveAny` unless:

* The block has been issued to consensus or
* The block is pending issuance

In either case, as you said, we must have already called `issue`...so I'm not sure why this changes the behavior of metric `avalanche_P_requests` for me

**Pull request closed without merging**
