### PR TITLE
Improves security by updating blst to version 0.3.12. Closes #3079

### LINKED ISSUE #3079: Update blst to 0.3.12
**Context and scope**

Currently `avalanchego` uses the version 0.3.11 of the library `blst` to implement the cryptographic signature BLS12-381.  The version 0.3.12 of `blst` improves security as described in its release notes https://github.com/supranational/blst/releases/tag/v0.3.12 and in particular includes the commits https://github.com/supranational/blst/commit/dae1f9416f157112be1dc46209a32ed5414fd525 and https://github.com/supranational/blst/commit/6cca12ac0c10ca8752d1788ee44891261c0f272a that

1. Improve security of the library by moving constants to a read-only section (not allowing attackers to modify the constants after the program starts)
2. Works with OpenBSD/adJ and advances #2782.  Due to security policies of that OS the previous version 0.3.11 with avalanchego produced segmentation faults sporadically, see https://github.com/supranational/blst/issues/206  The issue was solved with the mentioned commits included in version 0.3.12.

**Discussion and alternatives**
IMHO it is a good security practice to update version of libraries periodically.

**Open questions**

### PR DESCRIPTION
**Pull request by vtamara**
## Why this should be merged

* Improves security.  Closes #3079
* Advances porting avalanchego to OpenBSD/adJ #2782 

## How this works

With updated sources I just ran:
```sh
go get github.com/supranational/blst@v0.3.12
go mod tidy
```

## How this was tested

Tested with avalanchego 1.11.10 ported to OpenBSD/adJ 7.5, running a node validating in testnet (see below comment of 31st July).

Details about the port of avalanchego 1.11.10 to OpenBSD/adJ that includes updating blst to version 0.3.12 at <https://github.com/vtamara/avalanchego/wiki/Porting-avalanchego-1.11.10-to-OpenBSD-adJ-7.5>

I also proposed and tested updating blst to vesion 0.3.12 in [coreth](https://github.com/ava-labs/coreth/pull/615), [subnet-evm](https://github.com/ava-labs/subnet-evm/pull/1258), [avalanche-network-runner](https://github.com/ava-labs/avalanche-network-runner/pull/725), and proposed updating in [avalanche-cli](https://github.com/ava-labs/avalanche-cli/issues/2074).

### CODE REVIEW

**Comment by StephenButtolph** [comment]
I think you'll need to run:
```
go mod tidy
```
to fix the CI issue

**Comment by vtamara** [comment]
> I think you'll need to run:
> 
> ```
> go mod tidy
> ```
> 
> to fix the CI issue

Thank you. Done.

**Comment by StephenButtolph** [comment]
I think we're going to need to look into this a bit more closely... (this library feels like a bit of a wildcard). So this might take a little bit to merge. But thank you for opening this.

**Comment by vtamara** [comment]
I want to inform that I have been testing my port of avalanchego (and other ava-labs tools) to OpenBSD/adJ, that includes this library blst 0.3.12 on a system that is validating testnet fuji.  Three days ago I did validation for one day with succes, and yesterday I started a validation for one month.

Transaction: https://subnets-test.avax.network/p-chain/tx/keQmoqe86iVJw2mf1uxrM6GuxBTwPJdoB2BKc9wFyofcNezTP

How it looks in test.core.app:
image

**Comment by vtamara** [comment]
> I want to inform that I have been testing the port of avalanchego (and other ava-labs tools) to OpenBSD/adJ, that uses the library blst 0.3.12 on a system that is validating in testnet fuji. Three days ago I did validation for one day with succes, and yesterday I started a validation for one month...

Operating the node (not very attentive) some days ago I solved an issue with memory (increasing memory limit) and few days ago the machine where the validator operates blocked (it could have relation with low disk space).  I moved the validator to a different machine running OpenBSD/adJ 7.5 and with more disk space --since that machine is behind a firewall I "discovered" the option `--public-ip`.  More details at points 2 and 4 of https://github.com/vtamara/avalanchego/wiki/Porting-avalanchego-1.11.10-to-OpenBSD-adJ-7.5

However just today I discovered <https://subnets-test.avax.network/validators/NodeID-6d4VNVPxnk8g4NHfFR2ombAz1W23454pw?validatorTab=health_check> and how useful is to diagnose problems.  Since I didn´t know several details needed to operate a validator the performance of my node doesn't look good:

image

To improve the situation from the configuration/operation realms is there a document that documents details like `--public-ip` the importance of opening port 9651 and 9650 (I opened both to the public).  Or for example security considerations (should I open those ports to just certain machines) and very practical details about the operation that I should be aware and that will not interfere with the goald of showgin that updating blst to version 0.3.12 doesn´t decrease stability or functionality?



wonder if ther. The new machine is behind a firewall and I was trying long time until I found the option `--public-ip`

**Comment by vtamara** [comment]
1. I started another month as validator in testnet
2. According to my interpretation of <https://raw.githubusercontent.com/ava-labs/avalanche-docs/master/scripts/avalanchego-installer.sh> for a validator, the port 9651 should be open to the public while the port 9650 should be closed (open just to administrators).

Now starting https://subnets-test.avax.network/validators/NodeID-6d4VNVPxnk8g4NHfFR2ombAz1W23454pw?validatorTab=health_check looks very good:

image

**Comment by vtamara** [comment]
Hi, now after 15 days my node keeps looking good:

image

I even have a delegator:

image

**Comment by vtamara** [comment]
The stability during one month was very good:

image

**Pull request closed without merging**
