### PR TITLE
Ansible: service_playbook.yml support for avalanchgo 1.4.5+

### PR DESCRIPTION
**Pull request by moreati**

### CODE REVIEW

**Comment by moreati** [comment]
@aaronbuchwald I hope I'm not overstepping the mark by reverting the change you made in  scripts/ansible/roles/avalanche_build/defaults/main.yml to the Ansible variable `repo_branch`, `repo_name`, and `repo_url`. I've tried to explain my reasoning in 7b05305.

Do you think this is a reasonable approach? Would you like any assistance with overriding these variables, or Ansible in general? I'd be happy to discuss here, or e.g. discord.

**Comment by aaronbuchwald** [comment]
This mostly looks good to me. What’s the purpose of switching from using git to https for the repo url?

Also, yes it would be very helpful if you could provide instructions for overriding those values as well. I typically use this to deploy a non standard branch, so I usually make small modifications to these files anyways, but if there’s a cleaner way I’d love to improve my workflow with ansible.

Much appreciated as always!

**Comment by moreati** [comment]
> What’s the purpose of switching from using git to https for the repo url?

A `git@github.com` URL requires authentication with an ssh key, An `https://github.com` URL allows the repo to be cloned anonymously. E.g.

```
$ ansible -i ~/src/avalanchego/scripts/ansible/inventories/raspberrypi.yml raspberrypi -m git -a "repo=https://github.com/ava-labs/avalanchego dest=/tmp/httpclone version=dev"
raspberrypi | CHANGED => {
    "after": "a13436551d97a33bb9af81bbeebde2eb4573cbe1",
    "before": null,
    "changed": true
}
$ ansible -i ~/src/avalanchego/scripts/ansible/inventories/raspberrypi.yml raspberrypi -m git -a "repo=git@github.com:ava-labs/avalanchego dest=/tmp/sshclone version=dev"
raspberrypi | FAILED! => {
    "changed": false,
    "cmd": "/usr/bin/git clone --origin origin '' /tmp/sshclone",
    "msg": "Cloning into '/tmp/sshclone'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.",
    "rc": 128,
    "stderr": "Cloning into '/tmp/sshclone'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n",
    "stderr_lines": [
        "Cloning into '/tmp/sshclone'...",
        "Host key verification failed.",
        "fatal: Could not read from remote repository.",
        "",
        "Please make sure you have the correct access rights",
        "and the repository exists."
    ],
    "stdout": "",
    "stdout_lines": []
}
```

**Comment by moreati** [comment]
> StephenButtolph changed the base branch from master to dev

Sorry, I forget that every time. Would it make sense to make dev the default branch on this repo?

**Comment by moreati** [comment]
> Also, yes it would be very helpful if you could provide instructions for overriding those values as well.

Say you're running [scripts/ansible/update_playbook.yml](https://github.com/ava-labs/avalanchego/blob/master/scripts/ansible/update_playbook.yml), using an inventory similar to to the Amazon EC2 example

https://github.com/ava-labs/avalanchego/blob/f3cc5feb5b32c44d81afe2cb1f406e1245224c32/scripts/ansible/inventories/examples/amazon.yml#L1-L7

Your command line would be something like

```sh
ansible-playbook -i your_inventory.yml update_playbook.yml
```

To override `repo_url`,and `repo_name` I'd recommend one of

1. Add a line to your inventory, as part of the `vars:` section: e.g. 
    ```yaml
        repo_name: ava-labs/avalanchego-internal
        repo_url: git@github.com:{{ repo_name }}
    ```
1. Override the variable on the command line, e.g.
    ```bash
    ansible-playbook -i your_inventory.yml update_playbook.yml -e repo_name=... -e repo_url=...
    ```

There are other options as well (e.g. a vars file, an encrypted vault for API keys etc, individual encrypted variables), but I think the above would cover your immediate need.

Hope that makes sense. Happy to talk you through it, or answer wider Ansible questions.

**Comment by StephenButtolph** [comment]
> Sorry, I forget that every time. Would it make sense to make dev the default branch on this repo?

I believe that making `dev` the default branch would result in `dev` being the branch to show up when loading https://github.com/ava-labs/avalanchego. Which `master` is still the latest version... But yeah it's a bit annoying...

**Review by StephenButtolph — APPROVED** [review]

**Comment by moreati** [comment]
thank you

**Pull request merged**
